id: A05536C6F
title: Aspiration for the Spread of the Teachings of the Eight Chariots of the Practice
  Lineage
type: translation
pechas:
- I75402220
- IEAF1374A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:19.079578
  last_modified_at: 2023-01-04 12:49:19.079598
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I75402220/A28C: '4876'
  IEAF1374A/94AE: '4876'
